# Generated by Django 2.0.6 on 2018-06-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caritem',
            unique_together={('cart_key', 'product')},
        ),
    ]
